POST http://localhost:3002/create
Content-Type: application/json

{
  "name": "Artur",
  "email": "arturcastrodossantos.com@gmail.commm",
  "password": "123456Am@",
  "phone": "(88) 996036338",
  "cpf": "801.528.450-38",
  "birthDateAt": "2006-02-24"
}
